"""empty message

Revision ID: 0bb87707beff
Revises: 25d05db97ab7
Create Date: 2020-10-27 12:03:35.772862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bb87707beff'
down_revision = '25d05db97ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    op.drop_table('user')
    op.add_column('users', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('phone_nb', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_nb')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'address')
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone_nb', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
