"""empty message

Revision ID: 22758d55909c
Revises: 
Create Date: 2020-10-29 11:46:50.194032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22758d55909c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokenblacklist')
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.create_table('tokenblacklist',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('token_type', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_identity', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('revoked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('revoked_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires', mysql.DATETIME(), nullable=False),
    sa.Column('issue_at', mysql.DATETIME(), nullable=False),
    sa.CheckConstraint('(`revoked` in (0,1))', name='tokenblacklist_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
