"""add table tokenblacklist

Revision ID: 450686940e88
Revises: fa3193733d51
Create Date: 2020-10-28 10:09:14.342154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '450686940e88'
down_revision = 'fa3193733d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TokenBlackList')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TokenBlackList',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('token_type', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_identity', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('revoked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('revoked_at', mysql.DATETIME(), nullable=False),
    sa.Column('expires', mysql.DATETIME(), nullable=False),
    sa.Column('issue_at', mysql.DATETIME(), nullable=False),
    sa.CheckConstraint('(`revoked` in (0,1))', name='TokenBlackList_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
